name: Validate Gradle Wrapper

on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: gradle/wrapper-validation-action@v1
